#!/usr/bin/env bash

rm -rf /var/www/deploy/corona-vk/unicorn.pid
touch /var/www/deploy/corona-vk/unicorn.pid
chmod +rw  /var/www/deploy/corona-vk/unicorn.pid
chmod g+rw /var/www/deploy/corona-vk/unicorn.pid
chmod o+rw /var/www/deploy/corona-vk/unicorn.pid

# bundle exec unicorn -E production -c /var/www/deploy/corona-vk/unicorn.pid &> /var/www/deploy/corona-vk/log/corona-vk-output.log
bundle exec unicorn -E development -c /var/www/deploy/corona-vk/unicorn.pid &> /var/www/deploy/corona-vk/log/corona-vk-output.log



